export const tasks = [
  {
    id: 1,
    title: 'Design Landing Page',
    description: 'Create a landing page for the new product launch.',
    assignedTo: 'Alice',
    dueDate: '2024-07-15',
    status: 'completed',
  },
  {
    id: 2,
    title: 'Develop API',
    description: 'Develop the backend API for user authentication.',
    assignedTo: 'Bob',
    dueDate: '2024-07-20',
    status: 'in-progress',
  },
  {
    id: 3,
    title: 'Write Documentation',
    description: 'Write user documentation for the new features.',
    assignedTo: 'Charlie',
    dueDate: '2024-07-25',
    status: 'completed',
  },
  {
    id: 4,
    title: 'Fix Bugs',
    description: 'Fix the reported bugs from the last release.',
    assignedTo: 'David',
    dueDate: '2024-07-18',
    status: 'in-progress',
  },
  {
    id: 5,
    title: 'Test New Features',
    description: 'Perform testing on the new features developed.',
    assignedTo: 'Eve',
    dueDate: '2024-07-22',
    status: 'in-progress',
  },
];
